posix. changed flags to allow strict, optionally

diff --git a/src/wl-select b/src/wl-select
--- a/src/wl-select
+++ b/src/wl-select
@@ -20,18 +20,40 @@
 #	bindsym $mod+Shift+p exec grim -g "$(wl-select)" - | wl-copy
 # 
 
-if [ "$1" = '-w' -o "$1" == '--wofi' ]; then
+
+for arg in "$@"; do
+	case "$arg" in
+		-w|--wofi)
+			WOFI_MODE=1
+			shift 1
+			;;
+		-r|--strict)
+			SLURP_FLAGS=-r
+			shift 1
+			;;
+		-*)
+			printf 'Invalid flag, ignoring: %s' "${arg}" >&2
+			shift 1
+			;;
+		--)
+			break
+			;;
+		*)
+			;;
+	esac
+done
+
+if [ -n "${WOFI_MODE}" ]; then
 	swaymsg -t get_tree | \
 		jq -r 'recurse(.nodes[], .floating_nodes[]) | select(.pid and .visible) | {name} + .rect | "\(.x),\(.y) \(.width)x\(.height) \(.name)"' | \
 		wofi \
 		--show dmenu \
 		--pre-display-cmd 'echo "%s" | cut -d" " -f3-' | \
 		awk '{print $1,$2}'
-
 else
 	# Uses slurp to spit out the region of the clicked-upon window
 	swaymsg -t get_tree | \
 		jq -r 'recurse(.nodes[], .floating_nodes[]) | select(.pid and .visible) | {name} + .rect | "\(.x),\(.y) \(.width)x\(.height) \(.name)"' | \
-		slurp -o
+		slurp -o ${SLURP_FLAGS}
 fi
 
